print("****Welcome to calculator:do some calculations here lol****")
a=int(input("Enter a number:"))
b=int(input("Enter a number:"))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)